name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build_and_test:
    runs-on: ubunut-latest

    strategy:
      fail-fast: false
      max-parallel: 4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js (20.x)
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Unit Tests
        run: pnpm run test
